apiVersion: v1
kind: Service
metadata:
  name: smart-manufacturing-service
  namespace: smart-manufacturing
spec:
  type: ClusterIP
  selector:
    app: smart-manufacturing-app
  ports:
    - port: 5000
      targetPort: 5000
