apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smart-manufacturing-mlops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/REPLACE_WITH_OWNER/REPLACE_WITH_REPOSITORY.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: smart-manufacturing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
